require 'vagrant-aws'
require './aws_creds'
profiles = Aws_Creds.new()
creds = profiles.get_creds('default')
Vagrant.configure('2') do |config|
    config.vm.box = 'aws_dummy'
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.provider 'aws' do |aws, override|
        aws.region = 'us-east-1'

        aws.instance_type = 't2.micro' #'t2.micro' #t2.medium
        aws.access_key_id = creds['aws_access_key_id']
        aws.secret_access_key = creds['aws_secret_access_key']
        aws.keypair_name = 'personal_ec2_hung135'
        aws.region = 'us-east-1'
        aws.ami = 'ami-011b3ccf1bd6db744' #redhat 7.6
        #aws.ami = 'ami-02da3a138888ced85'  #amazon ami
        #aws.ami = 'ami-0a313d6098716f372' # ubuntu 1804
        aws.security_groups = ['default']
        override.ssh.username = 'ec2-user'
        override.ssh.private_key_path = '~/.ssh/personal_ec2_hung135.pem'
        aws.tags = {
	  'Name' => 'Vagrant-Aurora',
	  'Creator' => 'Hung',
      'hostname'=>'file_server_1'
        }
    end
end
# aws ec2 create-key-pair --key-name personal_ec2_key_pair --dry-run --profile personal --region us-east-1 > ~/.ssh/personal_ec2_key_pair.pem

# vagrant box add aws_dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
# need to set smb
# https://www.vagrantup.com/docs/synced-folders/smb.html
# https :/ / github.com / mitchellh / vagrant - aws
