# main.yml - Sets up a glusterfs file server node
---
- name: Install required packages
  yum:
    name: centos-release-gluster41
    state: latest
  when: not custom_repo and ansible_distribution == 'CentOS' 

- name: Download Create Gluster Red Hat repo
  #shell: "curl --silent --location {{jenkins_repo_url}} | sudo tee /etc/yum.repos.d/Gluster.repo"
  shell: "wget -P /etc/yum.repos.d/ http://download.gluster.org/pub/gluster/glusterfs/LATEST/CentOS/glusterfs-epel.repo"
  args:
    creates: "/etc/yum.repos.d/Gluster.repo"
  when: ansible_distribution == 'Red Hat Enterprise Linux'

# - name: upgrade all packages
#   yum: name=* state=latest
  
- name: Install required GlusterFS Centos packages
  yum:
    name: glusterfs-server
    state: latest
  when: ansible_distribution == 'CentOS'

- name: Install required GlusterFS Red-Hat packages
  yum:
    name: glusterfs
    state: latest
  when: ansible_distribution == 'Red Hat Enterprise Linux'
  

- name: Enable gluster server
  service:
    name: glusterd
    enabled: yes
    state: started
  when: ansible_distribution == 'CentOS' # what is service name for RHEL?

- name: Open ports
  command: "iptables -I {{ iptables_chain }} 3 -m state --state NEW -p tcp --dport {{ item }} -j ACCEPT"
  with_items:
    - 111
    - "24007:24008"
    - "49152:49154"
  when: iptables_config

- name: Save iptables config
  command: "/sbin/service iptables save"
  notify:
    - restart iptables
  when: iptables_config
