# deploy_file_server.yml
---
- hosts: file_server
  become: yes
  become_method: sudo
  pre_tasks:
    - name: Install libselinux-python
      yum:
        name: libselinux-python
        state: latest

  roles:
    - epel
    - {role: puppet_disable, when: "disable_puppet"}
    - iptables

    - ntp
    - glusterfs
    - {role: log-courier, when: "install_logstash"}
    - odbc

  tasks:
    - name: Create the Filesystem
      filesystem:
        fstype: ext4
        dev: /dev/xvdb #this breaks virtual box

    - name: Mount volume
      mount:
        name: /data
        src: /dev/xvdb
        fstype: ext4
        state: mounted

    - name: Ensure directories exist
      file:
        state: directory
        dest: /data/{{ item }}
      with_items: shared_folders
