cat /workspace/.devcontainer/welcome.txt
echo "Fish is your friend!!!"
echo "TYPE ""fish"""
alias deploy="ansible-playbook /workspace/deploy/deploy_citus_server.yml -i /workspace/deploy/vagrant_hosts --ask-pass --user=super --ask-sudo-pass" 